### PR TITLE
#76 added supporting of exiting from app; Android only

### PR DESCRIPTION
**Pull request by CSeal**
**What?**
#76 Warning when exiting the app
added supporting of exit from the app

**Why?**
It is able users to choose another Firestick app. 

**How?**

added additional item(button) to nav menu. added modal with exit`s question.

works only on Android devices. For iOS need to find another approach
https://github.com/wumke/react-native-exit-app  as example 

**How to test?**

press on the exit button at bottom of the nav menu. you will see the modal screen with the exit`s question. If you will agree with it the app will clear all states and close. It will be equal if you press the back button on the remote control in the main screens as home screen, search screen, and so on.

### CODE REVIEW

**Comment by tomdyson** [comment]
I believe we've decided not to have an exit warning for now - @mark-weber to confirm.

**Comment by mark-weber** [comment]
confirmed, was agreed to move to post-launch (it was moved out of the week 22 milestone work) @CSeal @tomdyson

**Comment by sinewave440hz** [comment]
We can put this in as a deactivated feature flag. We have the flagged library in the app for this! I've tested it and it works fine, both selecting no and yes. 
image
Perhaps though we should pre-select No rather than Yes...

**Review by sinewave440hz — CHANGES_REQUESTED** [review]
- Put it in a feature flag.
- Pre-select No rather than Yes (IMO)

**Pull request merged**
